server:
  port: 9070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fashion_shop
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations: classpath:/static/



jwt:
  secret: ${JWT_SECRET:12^5$#neded#*&#$#^&$#$6343}
  expiration: 36000000

